### ISSUE TITLE
Run prettier after codegen

### ISSUE THREAD

**Issue by wtrocki** [RedHat-Middleware-Workshops/rhtr-2020-api-mgmt-kafka-workshop#5]
Codegen can format things wrong way. It is best way to configure scripts to run prettier after. 
Current build is failing because of it

https://github.com/RedHat-Middleware-Workshops/rhtr-2020-api-mgmt-kafka-workshop/runs/1148872561

CC @evanshortiss

**Comment by evanshortiss** [comment]
Ah good point. I considered adding huksy for pre-commit hooks, but doing that in a project with multiple services might be a pain. Will add prettier call in the codegen npm script 👍
